site_name: Torch Lens Maker

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    # - toc.integrate
  palette:
    - scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocs-jupyter

nav:
  - Home: index.md
  - Examples:
    - Aperture: 'examples_executed/Aperture.ipynb'
    - Biconvex Diverging Lens: 'examples_executed/Biconcave diverging lens.ipynb'
    - Biconvex lens bezier Spline: 'examples_executed/Biconvex lens bezier spline.ipynb'
    - Biconvex lens parabola: 'examples_executed/Biconvex lens parabola.ipynb'
  - Reference:
    - Shapes: reference/shapes.md
    - Lenses: reference/lenses.md
  - About: about.md