site_name: Torch Lens Maker

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    # - toc.integrate
  palette:
    - scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocs-jupyter

nav:
  - Home: index.md
  - Examples:
    - Simple Lenses:
      - Biconvex lens (sphere): examples_executed/Biconvex lens sphere.ipynb
      - Biconvex lens (parabola): examples_executed/Biconvex lens parabola.ipynb
      - Biconvex lens (bezier spline): examples_executed/Biconvex lens bezier spline.ipynb
      - Biconcave diverging lens: examples_executed/Biconcave diverging lens.ipynb
      - Planoconvex lens (sphere): examples_executed/Planoconvex lens (sphere).ipynb
      - Planoconvex lens (piecewise line): examples_executed/Planoconvex lens (piecewise line).ipynb

    - Multiple Lenses:
      - Variable number of lenses: examples_executed/Multiple Lenses Sequence.ipynb
      - Triple Lens: examples_executed/Triple Biconvex lens parabola.ipynb
      - Optimization without tlm.Module: examples_executed/Biconvex Parabola - No tlmModule.ipynb
      - Moving a lens to focus: examples_executed/Moving a lens to focus.ipynb
      - Regularization - Equal Thickness Lenses: examples_executed/Regularization - Equal Thickness Lenses.ipynb
  
    - Mirrors:
      - Reflecting Telescope: examples_executed/Reflecting Telescope.ipynb
      - Concave Mirror: examples_executed/Concave Mirror.ipynb
    
    - Optics:
      - Aperture: examples_executed/Aperture.ipynb
      - Surface Anchors: examples_executed/Surface anchors.ipynb

  - Reference:
    - Shapes: reference/shapes.md
    - Lenses: reference/lenses.md
