[project]
name = "torchlensmaker"
version = "0.0.1"
authors = [
  { name="Victor Poughon", email="victor.poughon@gmail.com" }
]
description = "Design optical systems with optimization"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
  "torch==2.4.1",
  "matplotlib==3.9.2",
  "jupyterlab==4.3.0",
  "build123d==0.7.0",
  "nbmake==1.5.4",
  "pytest==8.3.3",
  "ipywidgets==8.1.5"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["torchlensmaker"]

[project.urls]
Homepage = "https://github.com/fouronnes/torchlensmaker"
Issues = "https://github.com/fouronnes/torchlensmaker/issues"
